chore: prepare 1.0 release
ntex-rs/website pull request #3
Opened 2024-01-09 11:05 UTC by leon3s

To be ready for when ntex 1.0 is out

2024-01-11 13:17 UTC, leon3s commented
Hey @fafhrd91 let me know if i missed something, i'm ready to deploy it as soon as you reviewed it.

2024-01-11 19:29 UTC, fafhrd91 requested changes

2024-01-11 19:29 UTC, fafhrd91 commented on examples/middleware/src/errorhandler.rs
> +    async fn call<'a>(&self, req: web::WebRequest<Err>, ctx: ServiceCtx<'a, Self>) -> Result<Self::Response, Self::Error> {
remove <‘a>, itnis not needed

2024-01-12 10:33 UTC, fafhrd91 approved these changes

2024-01-12 10:36 UTC, merged